Issue41 adicionar campo hashid ao usuario
gfborges/uol-unique-user-id pull request #45
Opened 2021-11-15 17:49 UTC by eduardoquerido

2021-11-16 12:30 UTC, gfborges requested changes

2021-11-16 12:30 UTC, gfborges commented on src/main/java/org/fatec/uniqueuserid/users/service/UserService.java
> +        return userRepository.findAll(Sort.by(Sort.Direction.ASC, "signUp.deviceId"));
pode mudar isso para o hashId ? Assim o pessoal vai agrupar os usuários únicos

2021-11-16 14:11 UTC, eduardoquerido commented on src/main/java/org/fatec/uniqueuserid/users/service/UserService.java
> +        return userRepository.findAll(Sort.by(Sort.Direction.ASC, "signUp.deviceId"));
blz, vou alterar isso hoje

2021-11-16 21:17 UTC, eduardoquerido commented on src/main/java/org/fatec/uniqueuserid/users/service/UserService.java
> +        return userRepository.findAll(Sort.by(Sort.Direction.ASC, "signUp.deviceId"));
feito!

2021-11-17 11:55 UTC, gfborges approved these changes

2021-11-17 11:55 UTC, merged